export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_REGISTERByADMIN_REQUEST = 'USER_REGISTERByADMIN_REQUEST'
export const USER_REGISTERByADMIN_SUCCESS = 'USER_REGISTERByADMIN_SUCCESS'
export const USER_REGISTERByADMIN_FAIL = 'USER_REGISTERByADMIN_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const SAPAR_LIST_REQUEST = 'SAPAR_LIST_REQUEST'
export const SAPAR_LIST_SUCCESS = 'SAPAR_LIST_SUCCESS'
export const SAPAR_LIST_FAIL = 'SAPAR_LIST_FAIL'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

export const MAKE_WORKINGDAY_REQUEST = 'MAKE_WORKINGDAY_REQUEST'
export const MAKE_WORKINGDAY_SUCCESS = 'MAKE_WORKINGDAY_SUCCESS'
export const MAKE_WORKINGDAY_FAIL = 'MAKE_WORKINGDAY_FAIL'

export const PICK_WORKINGDAY_REQUEST = 'PICK_WORKINGDAY_REQUEST'
export const PICK_WORKINGDAY_SUCCESS = 'PICK_WORKINGDAY_SUCCESS'
export const PICK_WORKINGDAY_RESET = 'PICK_WORKINGDAY_RESET'
export const PICK_WORKINGDAY_FAIL = 'PICK_WORKINGDAY_FAIL'

export const WORKING_DAYS_REQUEST = 'WORKING_DAYS_REQUEST'
export const WORKING_DAYS_SUCCESS = 'WORKING_DAYS_SUCCESS'
export const WORKING_DAYS_FAIL = 'WORKING_DAYS_FAIL'

export const ONE_WORKING_DAY_REQUEST = 'ONE_WORKING_DAY_REQUEST'
export const ONE_WORKING_DAY_SUCCESS = 'ONE_WORKING_DAY_SUCCESS'
export const ONE_WORKING_DAY_FAIL = 'ONE_WORKING_DAY_FAIL'

export const LIST_WORKING_DAYS_FOR_THIS_WEEK_REQUEST =
  'LIST_WORKING_DAYS_FOR_THIS_WEEK_REQUEST'
export const LIST_WORKING_DAYS_FOR_THIS_WEEK_SUCCESS =
  'LIST_WORKING_DAYS_FOR_THIS_WEEK_SUCCESS'
export const LIST_WORKING_DAYS_FOR_THIS_WEEK_FAIL =
  'LIST_WORKING_DAYS_FOR_THIS_WEEK_FAIL'

export const WORKING_DAY_DELETE_REQUEST = 'WORKING_DAY_DELETE_REQUEST'
export const WORKING_DAY_DELETE_SUCCESS = 'WORKING_DAY_DELETE_SUCCESS'
export const WORKING_DAY_DELETE_FAIL = 'WORKING_DAY_DELETE_FAIL'
export const WORKING_DAY_DELETE_RESET = 'WORKING_DAY_DELETE_RESET'

export const WORKING_DAY_DETAILS_REQUEST = 'WORKING_DAY_DETAILS_REQUEST'
export const WORKING_DAY_DETAILS_SUCCESS = 'WORKING_DAY_DETAILS_SUCCESS'
export const WORKING_DAY_DETAILS_FAIL = 'WORKING_DAY_DETAILS_FAIL'

export const MAKE_CLOCK_REQUEST = 'MAKE_CLOCK_REQUEST'
export const MAKE_CLOCK_SUCCESS = 'MAKE_CLOCK_SUCCESS'
export const MAKE_CLOCK_FAIL = 'MAKE_CLOCK_FAIL'
export const MAKE_CLOCK_SUCSSES_RESET = 'MAKE_CLOCK_SUCSSES_RESET'

export const MAKE_CLOCKS_REQUEST = 'MAKE_CLOCKS_REQUEST'
export const MAKE_CLOCKS_SUCCESS = 'MAKE_CLOCKS_SUCCESS'
export const MAKE_CLOCKS_FAIL = 'MAKE_CLOCKS_FAIL'
export const MAKE_CLOCKS_SUCSSES_RESET = 'MAKE_CLOCKS_SUCSSES_RESET'

export const CLOCK_LIST_REQUEST = 'CLOCK_LIST_REQUEST'
export const CLOCK_LIST_SUCCESS = 'CLOCK_LIST_SUCCESS'
export const CLOCK_LIST_FAIL = 'CLOCK_LIST_FAIL'

export const SEND_NotificationSMS_REQUEST = 'SEND_NotificationSMS_REQUEST'
export const SEND_NotificationSMS_SUCCESS = 'SEND_NotificationSMS_SUCCESS'
export const SEND_NotificationSMS_FAIL = 'SEND_NotificationSMS_FAIL'

export const BookMEonGoogleCalender_REQUEST = 'BookMEonGoogleCalender_REQUEST'
export const BookMEonGoogleCalender_SUCCESS = 'BookMEonGoogleCalender_SUCCESS'
export const BookMEonGoogleCalender_FAIL = 'BookMEonGoogleCalender_FAIL'

export const GoogleLogin_REQUEST = 'GoogleLogin_REQUEST'
export const GoogleLogin_SUCCESS = 'GoogleLogin_SUCCESS'
export const GoogleLogin_FAIL = 'GoogleLogin_FAIL'

export const CLOCK_DELETE_REQUEST = 'CLOCK_DELETE_REQUEST'
export const CLOCK_DELETE_SUCCESS = 'CLOCK_DELETE_SUCCESS'
export const CLOCK_DELETE_FAIL = 'CLOCK_DELETE_FAIL'
export const CLOCK_DELETE_RESET = 'CLOCK_DELETE_RESET'

export const MAKE_WORKINGDAY_RESET = 'MAKE_WORKINGDAY_RESET'

export const CONFIRM_TOR_REQUEST = 'CONFIRM_TOR_REQUEST'
export const CONFIRM_TOR_SUCCESS = 'CONFIRM_TOR_SUCCESS'
export const CONFIRM_TOR_FAIL = 'CONFIRM_TOR_FAIL'
export const CONFIRM_TOR_RESET = 'CONFIRM_TOR_RESET'

export const AVILABLE_WORKINGDAY_TORS_REQUEST =
  'AVILABLE_WORKINGDAY_TORS_REQUEST'
export const AVILABLE_WORKINGDAY_TORS_SUCCESS =
  'AVILABLE_WORKINGDAY_TORS_SUCCESS'
export const AVILABLE_WORKINGDAY_TORS_FAIL = 'AVILABLE_WORKINGDAY_TORS_FAIL'

export const TORIM_LIST_MY_REQUEST = 'TORIM_LIST_MY_REQUEST'
export const TORIM_LIST_MY_SUCCESS = 'TORIM_LIST_MY_SUCCESS'
export const TORIM_LIST_MY_FAIL = 'TORIM_LIST_MY_FAIL'
export const TORIM_LIST_MY_RESET = 'TORIM_LIST_MY_RESET'

export const CANCEL_TOR_REQUEST = 'CANCEL_TOR_REQUEST'
export const CANCEL_TOR_SUCCESS = 'CANCEL_TOR_SUCCESS'
export const CANCEL_TOR_FAIL = 'CANCEL_TOR_FAIL'
export const CANCEL_TOR_RESET = 'CONFIRM_TOR_RESET'

export const PAY_TOR_REQUEST = 'PAY_TOR_REQUEST'
export const PAY_TOR_SUCCESS = 'PAY_TOR_SUCCESS'
export const PAY_TOR_FAIL = 'PAY_TOR_FAIL'
export const PAY_TOR_RESET = 'PAY_TOR_RESET'

export const UNPAY_TOR_REQUEST = 'UNPAY_TOR_REQUEST'
export const UNPAY_TOR_SUCCESS = 'UNPAY_TOR_SUCCESS'
export const UNPAY_TOR_FAIL = 'UNPAY_TOR_FAIL'
export const UNPAY_TOR_RESET = 'UNPAY_TOR_RESET'

export const SEND_SMS_TOR_REQUEST = 'SEND_SMS_TOR_REQUEST'
export const SEND_SMS_TOR_SUCCESS = 'SEND_SMS_TOR_SUCCESS'
export const SEND_SMS_TOR_FAIL = 'SEND_SMS_TOR_FAIL'
export const SEND_SMS_TOR_RESET = 'SEND_SMS_TOR_RESET'

export const SEND_Cancel_SMS_TOR_REQUEST = 'SEND_Cancel_SMS_TOR_REQUEST'
export const SEND_Cancel_SMS_TOR_SUCCESS = 'SEND_Cancel_SMS_TOR_SUCCESS'
export const SEND_Cancel_SMS_TOR_FAIL = 'SEND_Cancel_SMS_TOR_FAIL'
export const SEND_Cancel_SMS_TOR_RESET = 'SEND_Cancel_SMS_TOR_RESET'

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST'
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL'

export const USER_GOOGLE_LOGIN_REQUEST = 'USER_GOOGLE_LOGIN_REQUEST'
export const USER_GOOGLE_LOGIN_SUCCESS = 'USER_GOOGLE_LOGIN_SUCCESS'
export const USER_GOOGLE_LOGIN_FAIL = 'USER_GOOGLE_LOGIN_FAIL'
export const USER_GOOGLE_LOGIN_RESET = 'USER_GOOGLE_LOGIN_RESET'

export const CLOCK_LIST_FOR_TODAY_REQUEST = 'CLOCK_LIST_FOR_TODAY_REQUEST'
export const CLOCK_LIST_FOR_TODAY_SUCCESS = 'CLOCK_LIST_FOR_TODAY_SUCCESS'
export const CLOCK_LIST_FOR_TODAY_FAIL = 'CLOCK_LIST_FOR_TODAY_FAIL'

export const CLOCK_LIST_FOR_THIS_WORK_DAY_REQUEST =
  'CLOCK_LIST_FOR_THIS_WORK_DAY_REQUEST'
export const CLOCK_LIST_FOR_THIS_WORK_DAY_SUCCESS =
  'CLOCK_LIST_FOR_THIS_WORK_DAY_SUCCESS'
export const CLOCK_LIST_FOR_THIS_WORK_DAY_FAIL =
  'CLOCK_LIST_FOR_THIS_WORK_DAY_FAIL'

export const CLOCK_LIST_FOR_THIS_MONTH_REQUEST =
  'CLOCK_LIST_FOR_THIS_MONTH_REQUEST'
export const CLOCK_LIST_FOR_THIS_MONTH_SUCCESS =
  'CLOCK_LIST_FOR_THIS_MONTH_SUCCESS'
export const CLOCK_LIST_FOR_THIS_MONTH_FAIL = 'CLOCK_LIST_FOR_THIS_MONTH_FAIL'

export const CLOCK_LIST_FOR_THIS_WEEK_REQUEST =
  'CLOCK_LIST_FOR_THIS_WEEK_REQUEST'
export const CLOCK_LIST_FOR_THIS_WEEK_SUCCESS =
  'CLOCK_LIST_FOR_THIS_WEEK_SUCCESS'
export const CLOCK_LIST_FOR_THIS_WEEK_FAIL = 'CLOCK_LIST_FOR_THIS_WEEK_FAIL'

export const ADMIN_CREATE_REPORT_REQUEST = 'ADMIN_CREATE_REPORT_REQUEST'
export const ADMIN_CREATE_REPORT_SUCCESS = 'ADMIN_CREATE_REPORT_SUCCESS'
export const ADMIN_CREATE_REPORT_FAIL = 'ADMIN_CREATE_REPORT_FAIL'

export const ADMIN_CREATE_REPORT_FOR_WEEK_REQUEST =
  'ADMIN_CREATE_REPORT_FOR_WEEK_REQUEST'
export const ADMIN_CREATE_REPORT_FOR_WEEK_SUCCESS =
  'ADMIN_CREATE_REPORT_FOR_WEEK_SUCCESS'
export const ADMIN_CREATE_REPORT_FOR_WEEK_FAIL =
  'ADMIN_CREATE_REPORT_FOR_WEEK_FAIL'

export const ADMIN_CREATE_REPORT_FOR_MONTH_REQUEST =
  'ADMIN_CREATE_REPORT_FOR_MONTH_REQUEST'
export const ADMIN_CREATE_REPORT_FOR_MONTH_SUCCESS =
  'ADMIN_CREATE_REPORT_FOR_MONTH_SUCCESS'
export const ADMIN_CREATE_REPORT_FOR_MONTH_FAIL =
  'ADMIN_CREATE_REPORT_FOR_MONTH_FAIL'

export const DAILY_REPORTS_LIST_REQUEST = 'DAILY_REPORTS_LIST_REQUEST'
export const DAILY_REPORTS_LIST_SUCCESS = 'DAILY_REPORTS_LIST_SUCCESS'
export const DAILY_REPORTS_LIST_FAIL = 'DAILY_REPORTS_LIST_FAIL'

export const Weekly_REPORTS_LIST_REQUEST = 'Weekly_REPORTS_LIST_REQUEST'
export const Weekly_REPORTS_LIST_SUCCESS = 'Weekly_REPORTS_LIST_SUCCESS'
export const Weekly_REPORTS_LIST_FAIL = 'Weekly_REPORTS_LIST_FAIL'

export const MONTHLY_REPORTS_LIST_REQUEST = 'MONTHLY_REPORTS_LIST_REQUEST'
export const MONTHLY_REPORTS_LIST_SUCCESS = 'MONTHLY_REPORTS_LIST_SUCCESS'
export const MONTHLY_REPORTS_LIST_FAIL = 'MONTHLY_REPORTS_LIST_FAIL'

export const GET_REPORT_DEETS_BY_ID_REQUEST = 'GET_REPORT_DEETS_BY_ID_REQUEST'
export const GET_REPORT_DEETS_BY_ID_SUCCESS = 'GET_REPORT_DEETS_BY_ID_SUCCESS'
export const GET_REPORT_DEETS_BY_ID_FAIL = 'GET_REPORT_DEETS_BY_ID_FAIL'

export const CREATE_NEW_TIPUL_REQUEST = 'CREATE_NEW_TIPUL_REQUEST'
export const CREATE_NEW_TIPUL_SUCCESS = 'CREATE_NEW_TIPUL_SUCCESS'
export const CREATE_NEW_TIPUL_FAIL = 'CREATE_NEW_TIPUL_FAIL'

export const SUGEI_TIPULIM_LIST_REQUEST = 'SUGEI_TIPULIM_LIST_REQUEST'
export const SUGEI_TIPULIM_LIST_SUCCESS = 'SUGEI_TIPULIM_LIST_SUCCESS'
export const SUGEI_TIPULIM_LIST_FAIL = 'SUGEI_TIPULIM_LIST_FAIL'

export const GET_TIPUL_DEETS_REQUEST = 'GET_TIPUL_DEETS_REQUEST'
export const GET_TIPUL_DEETS_SUCCESS = 'GET_TIPUL_DEETS_SUCCESS'
export const GET_TIPUL_DEETS_FAIL = 'GET_TIPUL_DEETS_FAIL'

export const ONE_USER_SEARCH_REQUEST = 'ONE_USER_SEARCH_REQUEST'
export const ONE_USER_SEARCH_SUCCESS = 'ONE_USER_SEARCH_SUCCESS'
export const ONE_USER_SEARCH_FAIL = 'ONE_USER_SEARCH_FAIL'

export const GET_ME_USER_ID_FOR_NO_AVILABLE_CLOCK_REQUEST =
  'GET_ME_USER_ID_FOR_NO_AVILABLE_CLOCK_REQUEST'
export const GET_ME_USER_ID_FOR_NO_AVILABLE_CLOCK_SUCCESS =
  'GET_ME_USER_ID_FOR_NO_AVILABLE_CLOCK_SUCCESS'
export const GET_ME_USER_ID_FOR_NO_AVILABLE_CLOCK_FAIL =
  'GET_ME_USER_ID_FOR_NO_AVILABLE_CLOCK_FAIL'
