export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

export const MAKE_WORKINGDAY_REQUEST = 'MAKE_WORKINGDAY_REQUEST'
export const MAKE_WORKINGDAY_SUCCESS = 'MAKE_WORKINGDAY_SUCCESS'
export const MAKE_WORKINGDAY_FAIL = 'MAKE_WORKINGDAY_FAIL'

export const WORKING_DAYS_REQUEST = 'WORKING_DAYS_REQUEST'
export const WORKING_DAYS_SUCCESS = 'WORKING_DAYS_SUCCESS'
export const WORKING_DAYS_FAIL = 'WORKING_DAYS_FAIL'

export const WORKING_DAY_DELETE_REQUEST = 'WORKING_DAY_DELETE_REQUEST'
export const WORKING_DAY_DELETE_SUCCESS = 'WORKING_DAY_DELETE_SUCCESS'
export const WORKING_DAY_DELETE_FAIL = 'WORKING_DAY_DELETE_FAIL'

export const WORKING_DAY_DETAILS_REQUEST = 'WORKING_DAY_DETAILS_REQUEST'
export const WORKING_DAY_DETAILS_SUCCESS = 'WORKING_DAY_DETAILS_SUCCESS'
export const WORKING_DAY_DETAILS_FAIL = 'WORKING_DAY_DETAILS_FAIL'

export const MAKE_CLOCK_REQUEST = 'MAKE_CLOCK_REQUEST'
export const MAKE_CLOCK_SUCCESS = 'MAKE_CLOCK_SUCCESS'
export const MAKE_CLOCK_FAIL = 'MAKE_CLOCK_FAIL'

export const CLOCK_LIST_REQUEST = 'CLOCK_LIST_REQUEST'
export const CLOCK_LIST_SUCCESS = 'CLOCK_LIST_SUCCESS'
export const CLOCK_LIST_FAIL = 'CLOCK_LIST_FAIL'

export const CLOCK_DELETE_REQUEST = 'CLOCK_DELETE_REQUEST'
export const CLOCK_DELETE_SUCCESS = 'CLOCK_DELETE_SUCCESS'
export const CLOCK_DELETE_FAIL = 'CLOCK_DELETE_FAIL'

export const MAKE_WORKINGDAY_RESET = 'MAKE_WORKINGDAY_RESET'
