export const BUSINESS_DETAILS_REQUEST = 'BUSINESS_DETAILS_REQUEST'
export const BUSINESS_DETAILS_SUCCESS = 'BUSINESS_DETAILS_SUCCESS'
export const BUSINESS_DETAILS_FAIL = 'BUSINESS_DETAILS_FAIL'

export const WORKERS_LIST_REQUEST = 'WORKERS_LIST_REQUEST'
export const WORKERS_LIST_SUCCESS = 'WORKERS_LIST_SUCCESS'
export const WORKERS_LIST_FAIL = 'WORKERS_LIST_FAIL'

export const TREATMENTS_LIST_REQUEST = 'TREATMENTS_LIST_REQUEST'
export const TREATMENTS_LIST_SUCCESS = 'TREATMENTS_LIST_SUCCESS'
export const TREATMENTS_LIST_FAIL = 'TREATMENTS_LIST_FAIL'
