export const BUSINESS_DETAILS_REQUEST = 'BUSINESS_DETAILS_REQUEST'
export const BUSINESS_DETAILS_SUCCESS = 'BUSINESS_DETAILS_SUCCESS'
export const BUSINESS_DETAILS_FAIL = 'BUSINESS_DETAILS_FAIL'

export const BUSINESS_DETAILS_FORNAV_REQUEST = 'BUSINESS_DETAILS_FORNAV_REQUEST'
export const BUSINESS_DETAILS_FORNAV_SUCCESS = 'BUSINESS_DETAILS_FORNAV_SUCCESS'
export const BUSINESS_DETAILS_FORNAV_FAIL = 'BUSINESS_DETAILS_FORNAV_FAIL'

export const WORKERS_LIST_REQUEST = 'WORKERS_LIST_REQUEST'
export const WORKERS_LIST_SUCCESS = 'WORKERS_LIST_SUCCESS'
export const WORKERS_LIST_FAIL = 'WORKERS_LIST_FAIL'

export const TREATMENTS_LIST_REQUEST = 'TREATMENTS_LIST_REQUEST'
export const TREATMENTS_LIST_SUCCESS = 'TREATMENTS_LIST_SUCCESS'
export const TREATMENTS_LIST_FAIL = 'TREATMENTS_LIST_FAIL'

export const BUSINESS_USER_REGISTER_REQUEST = 'BUSINESS_USER_REGISTER_REQUEST'
export const BUSINESS_USER_REGISTER_SUCCESS = 'BUSINESS_USER_REGISTER_SUCCESS'
export const BUSINESS_USER_REGISTER_FAIL = 'BUSINESS_USER_REGISTER_FAIL'

export const BUSINESS_USER_LOGIN_REQUEST = 'BUSINESS_USER_LOGIN_REQUEST'
export const BUSINESS_USER_LOGIN_SUCCESS = 'BUSINESS_USER_LOGIN_SUCCESS'
export const BUSINESS_USER_LOGIN_FAIL = 'BUSINESS_USER_LOGIN_FAIL'
